# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_done',
        ),
    ]
